In [7]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 70])

for j in i:
   
    print(j)

10
20
30
40
50
70


In [9]:
i = np.array([[10, 20, 30], [40, 50, 60], [70,80,90]])           #Access 2-D Element

for j in i:

    print(j)


[10 20 30]
[40 50 60]
[70 80 90]


In [11]:
import numpy as np

i = np.array([[10, 20, 30], [40, 50, 60], [70,80,90]])

for j in i:

    for k in j:                         #nested for loop

        print(k)


10
20
30
40
50
60
70
80
90


In [15]:
import numpy as np

i = np.array([
        [[10, 20, 30], [40, 50, 60], [70,80,90]],
        [[1, 2, 3], [4, 5, 6], [7,8,9]],
        [[10, 20, 30], [40, 50, 60], [70,80,90]],
])

for j in i:

    for k in j:

        for m in k:

            print(m)

10
20
30
40
50
60
70
80
90
1
2
3
4
5
6
7
8
9
10
20
30
40
50
60
70
80
90


In [17]:
 import numpy as np
i = np.array([
        [[10, 20, 30], [40, 50, 60], [70,80,90]],
        [[1, 2, 3], [4, 5, 6], [7,8,9]],
        [[10, 20, 30], [40, 50, 60], [70,80,90]],
])
for j in i:                              #Access 3-D Elements

    print(j)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
